development:
  bucket: teacher_mgnt 
  access_key_id: AKIAIOYCWZFROQJEEBYQ
  secret_access_key: 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
  max_file_size: 104857600
  acl: public-read
    
test:
  bucket: 
  access_key_id: 
  secret_access_key: 
  max_file_size: 104857600
  acl: public-read
  
production:
  bucket: teacher_mgnt  
  access_key_id: AKIAIOYCWZFROQJEEBYQ
  secret_access_key: 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
  max_file_size: 104857600
  acl: public-read

staging:
  bucket: teacher_mgnt  
  access_key_id: AKIAIOYCWZFROQJEEBYQ
  secret_access_key: 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
  max_file_size: 104857600
  acl: public-read
