development:
  database: teacher-dev
  capsize: <%= 10.megabytes %>
  host: localhost
  port: 27017
  replica_set: true

staging:
  url: <%= ENV['MONGOLAB_URI'] %>
  capsize: <%= 100.megabytes %>
  replica_set: true

production:
  database: teacher-dev
  capsize: <%= 10.megabytes %>
  host: localhost
  port: 27017
  replica_set: true

test:
  database: teacher-test
  capsize: <%= 2.megabytes %>
  host: localhost
  port: 27017
  replica_set: true
