development:
  database: teacher-dev
  capsize: <%= 10.megabytes %>
  host: localhost
  port: 27017
  replica_set: true

production:
  url: <%= ENV['MONGOLAB_URI'] %>
  capsize: <%= 100.megabytes %>
  replica_set: true
  disable_file_logging: true
