development:
  database: teacher-dev
  capsize: <%= 10.megabytes %>
  host: localhost
  port: 27017
  replica_set: true

production:
  database: heroku_app8243023
  capsize: <%= 100.megabytes %>
  host: s045507.mongolab.com
  port: 45507
  username: heroku_app8243023
  password: kfk2j30e2v85e7241p6nlah23j
